### PR TITLE
REM-696

### PR DESCRIPTION
**Pull request by imtithalhalalo**
adding new page plant supervisors

### CODE REVIEW

**Comment by omarZrayka23** [comment]
Screenshot 2024-11-20 at 3 23 59 PM

**Comment by omarZrayka23** [comment]
Screenshot 2024-11-20 at 4 32 29 PM

When I click, I see Fatima's name in Omar's user column email.

**Comment by omarZrayka23** [comment]
Screenshot 2024-11-21 at 12 20 17 PM
Screenshot 2024-11-21 at 12 20 44 PM

When a cell in this column is clicked (edit cell), the column's width changes.

**Comment by omarZrayka23** [comment]
Screenshot 2024-11-21 at 12 20 59 PM

**Review by omarZrayka23 — APPROVED** [review]

**Comment by NoraBitarSM** [comment]
i can't add users in this case
image

**Pull request merged**
