### PR TITLE
Rm 35

### PR DESCRIPTION
**Pull request by RebeccaFrem02**
made the fields smaller 
added customCheckbox and customRadioButtonGroup as two new shared components, you can test them in cash-invoice, currency-trading-new sales-order and bp-master-data pages and please test the maxAccess also
and made some styling changes

### CODE REVIEW

**Comment by Ghinwa-Arab** [comment]
image

image

**Comment by FatimaSalami** [comment]
image

**Comment by FatimaSalami** [comment]
image
is it normal to have the fields unaligned?

**Comment by FatimaSalami** [comment]
image
image
is this a global bug in expanding screen? it is the same on deploy but it is either from the code, or global so i guess it is time to fix it

**Comment by FatimaSalami** [comment]
image
i don't know if this is normal because the field is small or it is not synchronized with the focus omar already did

**Pull request merged**
