### PR TITLE
fix date shift problem

### PR DESCRIPTION
**Pull request by FatimaSalami**
we had previously in outbound screen -where time is attached to date and sent to api then cracked and displayed in popup- a problem in time where this leads to changes in date helper file

now another changes were made to keep this behaving properly
and to solve another appearing problem of choosing a date then getting on display day before or after in activities

for testing you can try in outbound, general journals, edit client.. and any other activities
we need please also to test dates in params selections

### CODE REVIEW

**Comment by imtithalhalalo** [comment]
Screenshot 2024-10-15 162414
here I am trying to post still showing the before date page:
Batch Post Credit Invoices
Batch Post Invoice
Rebuild Retail Invoice
Batch Post Return On Invoice
Batch Sync Sales Order

**Comment by imtithalhalalo** [comment]
Screenshot 2024-10-15 163528
even if there is value it is showing required :
pages :
Doc Level Commission, Sales Person Level Commission And POS Balance

**Comment by RebeccaFrem02** [comment]
image
image
start date is showing the day before on post

**Comment by RebeccaFrem02** [comment]
image
image
start date is showing the day before on post

**Comment by Ghinwa-Arab** [comment]
image

 'Start time' field, there is a difference 3 hours between saved value and returned value

**Pull request merged**
